# Generated by Django 2.0.6 on 2018-06-24 10:43

import django.contrib.postgres.fields
from django.db import migrations, models
import mastermind.game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='secret_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=mastermind.game.models.generate_secret_code, editable=False, size=None),
        ),
    ]
