# Generated by Django 2.0.6 on 2018-06-24 11:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180624_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
